#!/bin/sh

echo "Making /usr/share/mediawiki/serialized for Wiki Configure extension."
mkdir /usr/share/mediawiki/serialized
echo "Making /usr/share/mediawiki/serialized accessable to apache."
chown -R www-data /usr/share/mediawiki/serialized

echo "Make LocalSettings.php editable by apache."
chown www-data /etc/mediawiki/LocalSettings.php

echo "Begin enablng mediawiki extensions"

mwenext CategoryTree.php
mwenext Cite.php
mwenext Footnote.php
mwenext NewestPages.php
mwenext ParserFunctions.php
mwenext SpecialRenameuser.php
mwenext SyntaxHighlight_GeSHi.php
mwenext poem.php
