#!/usr/bin/env python
#Install the content of the wiki that will be visible on fresh install
# FAQ:
# Q: Why on earth are we installing content this way? 
# A: Believe it or not, this seems like the easiest way to load content in the wiki. 
#    We already developed a system to save and restore the entire wiki. So we will just
#    use that on first boot to install a default instance of content on the wiki.

DB_FILE = "/usr/share/innobox-wiki/defaultWikiContent.sql" 

def _run(cmd):
        from subprocess import Popen
        p = Popen(cmd, shell=True)
        p.communicate()
        return p.returncode

def load_database(filename, password):
        return _run('mysql -uwiki_user -p%s wiki_db < %s' % (password,filename))

def get_password():
        f = open('/etc/mediawiki/wiki_password.txt')
	# The password is the contents of the file, minus any trailing
	# white space.
        s = f.read().rstrip()
        f.close()
        return s

_run('/etc/init.d/mysql start')
print "Installing fresh Innobox Wiki contents into the mySQL databse..."
load_database(DB_FILE,get_password())
_run('/etc/init.d/mysql stop')
