#!/bin/sh
# Use the pwgen utility to write a 20-character secure random password
# to the wiki_password.txt.  The contents of the file will be the password,
# followed by a newline (\n).


#    Copyright 2010 InnoBox Devices <code@innoboxdevices.com>
#    This file is part of InnoBox Wiki Patch.
#
#    InnoBox Backup is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    InnoBox Wiki is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with InnoBox Wiki Patch.  If not, see <http://www.gnu.org/licenses/>.


pwgen -s 20 1 > /etc/mediawiki/wiki_password.txt
