#!/usr/bin/env python
import re

def get_pw(filename):
	f = open(filename,'r')
	r = re.compile(r'\$wgDBpassword = "(?P<pw>.*)";$')
	for line in f:
		m = r.search(line)
		if m:
			return m.group('pw')

def main():
	LSPATH = '/etc/mediawiki/LocalSettings.php'
	PWPATH = '/etc/mediawiki/wiki_password.txt'
	pw = get_pw(LSPATH)
	f = open(PWPATH,'w')
	f.write(pw)
	f.close()
	# FIXME: Handle error conditions

if __name__ == '__main__':
	main()
