#!/bin/sh
# Use the pwgen utility to write a 20-character secure random password
# to the wiki_password.txt.  The contents of the file will be the password,
# followed by a newline (\n).
pwgen -s 20 1 > /etc/mediawiki/wiki_password.txt
